# Generated by Django 4.2.30 on 2026-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionconfig',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse'), ('oracle', 'Oracle')], max_length=20),
        ),
    ]
